#!/usr/bin/env bash

if [ ! -d util ]; then
  echo "Please run this from the root of your repository"
  exit 1
fi

docker run --rm -it \
  --network host \
  -v $(pwd):/home/node/$(basename $(pwd)) \
  -v $(pwd)/util/bootstrap:/home/node/.bootstrap \
  -v ~/.gitconfig:/home/node/.gitconfig \
  --user node \
  --workdir /home/node \
  node:10-stretch bash --rcfile /home/node/.bootstrap
